from pathlib import Path
from asset_resolver import AssetResolver
from body_sanitizer import BodySanitizer
from folder_heading_builder import FolderHeadingBuilder
from heading_transformer import HeadingTransformer
from merge_configuration import MergeConfiguration
from parsed_document import ParsedDocument
from preamble_collector import PreambleCollector


class LatexProjectMerger:
    def __init__(self, configuration: MergeConfiguration, preamble_collector: PreambleCollector, heading_transformer: HeadingTransformer, folder_heading_builder: FolderHeadingBuilder, body_sanitizer: BodySanitizer, asset_resolver: AssetResolver) -> None:
        self.configuration = configuration
        self.preamble_collector = preamble_collector
        self.heading_transformer = heading_transformer
        self.folder_heading_builder = folder_heading_builder
        self.body_sanitizer = body_sanitizer
        self.asset_resolver = asset_resolver
        self.warnings = []

    def merge(self, documents: list[ParsedDocument]) -> tuple[str, list[str]]:
        self.preamble_collector.collect(documents)
        body_sections = self.build_body_sections(documents)
        tex_content = self.render_document(body_sections)
        self.warnings.extend(self.preamble_collector.warnings)
        self.warnings.extend(self.asset_resolver.warnings)
        return tex_content, self.warnings

    def build_body_sections(self, documents: list[ParsedDocument]) -> list[str]:
        body_sections = []
        for document in documents:
            if document.is_preamble_fragment:
                continue
            sanitized_body = self.body_sanitizer.sanitize(document.body)
            if not sanitized_body:
                continue
            folder_heading = self.folder_heading_builder.build_for_path(document.source_file.path)
            folder_depth = self.folder_heading_builder.folder_depth_for_path(document.source_file.path)
            transformed_body = self.heading_transformer.transform(sanitized_body, folder_depth)
            transformed_body = self.asset_resolver.transform(transformed_body, document.source_file.path)
            section_parts = []
            if folder_heading:
                section_parts.append(folder_heading)
            section_parts.append(f"% Source: {document.source_file.relative_path}")
            section_parts.append(transformed_body)
            body_sections.append("\n\n".join(section_parts))
        return body_sections

    def render_document(self, body_sections: list[str]) -> str:
        preamble_text = self.preamble_collector.render()
        compatibility_preamble = self.render_compatibility_preamble()
        bibliography_text = self.render_bibliography_commands()
        document_parts = [
            "% !TeX program = lualatex",
            "% Generated by the object-oriented LaTeX project merger.",
            f"\\documentclass{{{self.configuration.document_class}}}",
        ]
        if preamble_text:
            document_parts.append(preamble_text)
        document_parts.append(compatibility_preamble)
        document_parts.append("\\begin{document}")
        document_parts.extend(body_sections)
        document_parts.append(bibliography_text)
        document_parts.append("\\end{document}")
        return "\n\n".join(document_parts) + "\n"

    def render_compatibility_preamble(self) -> str:
        return r'''% Compatibility commands added by the merger.
\providecommand{\ProjectDeepHeading}[2]{%
    \par\medskip\noindent\textbf{#2}\par\smallskip
}
\providecommand{\ProjectMissingAsset}[1]{%
    \par\medskip\noindent\fbox{\parbox{0.9\linewidth}{Missing asset: \texttt{#1}}}\par\medskip
}
\providecommand{\ProjectSafeIncludeGraphics}[2][]{\includegraphics[#1]{#2}}
\providecommand{\ProjectSafeIncludePdf}[2][]{\includepdf[#1]{#2}}
\providecommand{\ProjectSafeIncludeSvg}[2][]{\includesvg[#1]{#2}}
\providecommand{\seehere}[1]{\href{#1}{see here}}
\providecommand{\seeherefooter}[1]{\footnote{\url{#1}}}
\providecommand{\clickurlfooter}[1]{\footnote{\url{#1}}}
\providecommand{\seefootnotehere}[1]{\footnote{\url{#1}}}
\providecommand{\semtag}[1]{\texttt{#1}}
\providecommand{\srcpath}[1]{#1}
\providecommand{\figspath}{}
\providecommand{\assetspath}{}
\providecommand{\figspathP}{}
\providecommand{\State}[1]{\ensuremath{#1}}
'''

    def render_bibliography_commands(self) -> str:
        bibliography_reference = self.configuration.bibliography_path.as_posix()
        return f"\\bibliographystyle{{plainnat}}\n    \\bibliography{{{bibliography_reference}}}"
